title: Anuradha Raidurg
subtitle: 
author: Anuradha
avatar_url: /assets/img/avatar.jpg  # Should be 160x160px.
description: > # this means to ignore newlines until "twitter_username:"
  Hellllooo there!!! 
  My name is Anuradha. I am a Human Resource professional. 
  I am crazy about reading and blogging. I am a big fashion and beauty freak. 
  I keep trying anything and everything which is new to the market. I post believable and sensible reviews to the viewers as 
  I would have personally experienced and used those products. I try to keep my post as simple as possible so that the viewers 
  can easily connect to the contents of the blog. Blogging is a great way to de-stress and that's how I catch up my me time. 
  Keep reading and encouraging with your valuable comments!! Read on :smile: Cheers!!!!!

# social links
#twitter_username: 
rss: rss

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown
excerpt_separator: <!--more-->

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: true
  show_count: true
  disqus_shortname: anuraidurg

emptyArray: [] # Leave this here.

# Haacked-Theme date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haacked-theme:
  date_format: "%-d %b %Y"

# Google Analytics
google_analytics: UA-78535445-2

#
# Jekyll Settings
#
permalink: /:year/:month/:day/:title/
paginate: 5 # number of posts per page
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/page:num/"
category_dir: categories

# Front matter defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji